Enumerable methods
belsman/Enumerable-Methods pull request #1
Opened 2020-09-09 15:21 UTC by belsman

2020-09-10 16:54 UTC, majovanilla requested changes
# Changes required :mag: 

Hey team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

You thought of almost all possible scenarios and your methods are passing most of the tests! That's awesome!

### There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Please check the comments I left on the code.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-09-10 16:54 UTC, majovanilla commented on .rubocop.yml
> +    - "Rakefile"
Please make sure you use the Microverse rubocop file and don't change it.

2020-09-10 16:54 UTC, majovanilla commented on README.md
> +
Please update the information of the Readme.

2020-09-10 16:54 UTC, majovanilla commented on my_enumerables.rb
> +  end
This method should work with Regex or a Class as a parameter.
Right now I get an error "Class or module required"
Example: `enumerable.my_all?(5)`

2020-09-10 16:54 UTC, majovanilla commented on my_enumerables.rb
> +  end
This method should work with Regex or a Class as a parameter.
Right now I get an error "Class or module required"
Example: `enumerable.my_any?(5)`
Example: `enumerable.my_any?('string')`

2020-09-10 16:54 UTC, majovanilla commented on my_enumerables.rb
> +  end
This method should work with Regex or a Class as a parameter.
Right now I get an error "Class or module required"
Example: `enumerable.my_any?(5)`
Example: `enumerable.my_any?('string')`

2020-09-10 16:54 UTC, majovanilla commented on my_enumerables.rb
> +    operator = nil
This method should work with ranges.
Example: `range.my_inject(:+)`

2020-09-11 15:00 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,
Thank you for applying the suggested changes 
However, there are some issues that need to be solve.
Kindly read the comments to learn more about them.
Once solved, kindly submit a new code review request.

Thanks

Mael FOSSO

2020-09-11 15:00 UTC, maelfosso commented on my_enumerables.rb
> +  end
```rb
2.6.5 :010 > array
 => [5, 5, 3, 1, 4, 2, 3, 8, 4, 2, 2, 8, 3, 8, 8, 4, 5, 7, 6, 7, 7, 7, 7, 5, 6, 6, 0, 2, 8, 8, 3, 4, 7, 1, 6, 5, 7, 4, 3, 1, 0, 6, 4, 8, 2, 1, 4, 8, 4, 8, 2, 1, 7, 0, 7, 1, 1, 8, 1, 8, 8, 0, 7, 8, 7, 5, 0, 0, 7, 3, 2, 4, 6, 8, 5, 8, 3, 8, 2, 6, 8, 5, 3, 0, 3, 5, 5, 6, 1, 2, 5, 8, 2, 2, 5, 3, 1, 7, 1, 6] 
2.6.5 :011 > operation = proc { |sum, n| sum + n }
2.6.5 :012 > array.my_inject(&operation)
 => 453 
2.6.5 :013 > array.my_inject(&operation)
 => 453 
2.6.5 :014 > array.inject(&operation)
 => 448 
2.6.5 :015 > array.inject(&operation)
 => 448 
2.6.5 :016 > 
```

2020-09-11 15:00 UTC, maelfosso commented on my_enumerables.rb
> +  end
```rb
2.6.5 :027 > array
 => [5, 5, 3, 1, 4, 2, 3, 8, 4, 2, 2, 8, 3, 8, 8, 4, 5, 7, 6, 7, 7, 7, 7, 5, 6, 6, 0, 2, 8, 8, 3, 4, 7, 1, 6, 5, 7, 4, 3, 1, 0, 6, 4, 8, 2, 1, 4, 8, 4, 8, 2, 1, 7, 0, 7, 1, 1, 8, 1, 8, 8, 0, 7, 8, 7, 5, 0, 0, 7, 3, 2, 4, 6, 8, 5, 8, 3, 8, 2, 6, 8, 5, 3, 0, 3, 5, 5, 6, 1, 2, 5, 8, 2, 2, 5, 3, 1, 7, 1, 6] 
2.6.5 :028 > array.inject(:+)
 => 448 
2.6.5 :029 > array.my_inject(:+)
 => 453 
2.6.5 :030 > 

```

2020-09-11 22:43 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:

#### You can merge !!!

2020-09-12 05:37 UTC, merged